# Database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bookshare}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:bookshare}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bookshare}

# Dev Tools
spring.devtools.livereload.enabled=true

# Mail
spring.mail.username=smzoha.dev@gmail.com
