# Database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bookshare}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:bookshare}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bookshare}

# Dev Tools
spring.devtools.livereload.enabled=true

# Mail
spring.mail.username=smzoha.dev@gmail.com

# Import Secrets
spring.config.import=optional:classpath:secret-dev.properties

# SpringDoc / Swagger UI
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.url=/api-docs/openapi.yaml
