-- Login SSO
ALTER TABLE logins ALTER COLUMN password DROP NOT NULL;

ALTER TABLE logins ADD COLUMN auth_provider VARCHAR(255) NOT NULL DEFAULT 'LOCAL';
ALTER TABLE logins ADD COLUMN provider_id VARCHAR(255);
