INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Romance', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Mystery / Crime', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Thriller / Suspense', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Fantasy', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Science Fiction', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Young Adult (YA)', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Historical Fiction', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Horror', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Adventure / Action', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Literary Fiction', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Magical Realism', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Steampunk', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Post-Apocalyptic / Dystopian', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Graphic Novels / Comics', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Contemporary Fiction', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Western', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Spy / Espionage', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Crime Noir', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Paranormal / Supernatural', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Chick Lit', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Biography / Memoir', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Self-Help / Personal Development', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'History', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'True Crime', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Science / Technology', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Politics / Social Issues', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Travel / Adventure Memoirs', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Cooking / Food', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Religion / Spirituality', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Art / Music / Culture', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Health & Fitness', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Parenting & Family', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Business / Entrepreneurship', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Psychology / Self-Improvement', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Essays / Opinion', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'How-To / DIY', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Nature / Environment', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Sports & Recreation', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Education / Learning', NOW());
INSERT INTO genre (id, name, created_at) VALUES (nextval('genre_seq'), 'Humor / Satire', NOW());
